### ISSUE TITLE
Still working ?

### ISSUE THREAD

**Issue by Varlin** [kellym/smartquotes.js#46]
Hi, is the script still working ?
When I load smartquotes.js and then write `smartquotes();`,
I get `ReferenceError: smartquotes is not defined`
Maybe I am missing something obvious...

**Comment by Varlin** [comment]
I tried with a blank test page to see if my Mediawiki installation interferes. 
I get no error message this time, but it does not work either :
https://wikirouge.net/nowiki/smartquotes.php

**Comment by kellym** [comment]
There's no error in console when calling `smartquotes` at the URL, so the method is defined.  You have no content on the page, so I'm not quite certain what the expectation is.  Have you tried with content on the page too?

**Comment by Varlin** [comment]
Oh... I thought the script was able to convert the quotes live, when typing in the textarea. My mistake...

**Comment by kellym** [comment]
The dynamic part described is when new nodes are added to the page. It's possible it could also be used live with some tweaking, some modifying text in a textarea in place and retaining the user's cursor position is a little more involved (nothing I haven't done before).

**Comment by Varlin** [comment]
Ok, thanks for the precisions
