### ISSUE TITLE
npm package read me needs to be updated

### ISSUE THREAD

**Issue by sunknudsen** [kellym/smartquotes.js#49]
> Visit the homepage at smartquotesjs.com. If you're planning on using this with node.js and express, try the express middleware express-smartquotes.

https://www.smartquotesjs.com/ is a dating website. On this GitHub repo, the URL is https://smartquotes.js.org/.

Perhaps I am missing something…

**Comment by kellym** [comment]
Ha, interesting. This used to be hosted on smartquotesjs.com but then we moved it to the js.org domain. Apparently someone else bought the domain.  Thanks for bringing this to my attention.

**Comment by kellym** [comment]
Oh, looks like maybe you were looking at an older commit. The most recent README has the correct website.

**Comment by sunknudsen** [comment]
@kellym Did you look at https://www.npmjs.com/package/smartquotes? Unless we’re experiencing a strange caching issue, `smartquotesjs.com` is there.

**Comment by kellym** [comment]
I totally missed the title of this issue. My apologies, you are correct. We just need to cut a new release.
